### ISSUE TITLE
npm-install giving errors

### ISSUE THREAD

**Issue by chetansharmapsi** [7kfpun/cors-proxy#1]
Hi, 
I am trying to use this project to deploy cors Firebase Cloud Function at Firebase project. I am following provided instructions but getting some issues.

Running `npm-install` at Firebase CLI giving following error logs :

```
> npm install
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

> core-js@2.6.12 postinstall D:\GitHub\cors-proxy\functions\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module 'D:\GitHub\cors-proxy\functions\node_modules\core-js\-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:608:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1355:46)
    at Function.Module._load (internal/modules/cjs/loader.js:524:27)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1384:12)
    at internal/main/run_main_module.js:17:11
npm WARN firebase-functions@0.6.3 requires a peer of firebase-admin@~5.2.1 but none is installed. You must install peer dependencies yourself.
npm WARN cors-proxy@1.0.0 No description
npm WARN cors-proxy@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-js@2.6.12 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-js@2.6.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chetan.sharma\AppData\Roaming\npm-cache\_logs\2021-05-12T05_56_54_909Z-debug.log 
```
Please guide me if I need to do some pre setup for this.

Thanks.

**Comment by chetansharmapsi** [comment]
After updating dependencies version, able to run `npm install` successfully, so closing this issue.
